Namespace 'GitHub.api',
  'GET /events': 'getEvents'
  'GET /repos/:owner/:repo/events': 'getRepoEvents'
  'GET /repos/:owner/:repo/issues/events': 'getRepoIssueEvents'
  'GET /networks/:owner/:repo/events': 'getPublicNetworkRepoEvents'
  'GET /orgs/:org/events': 'getOrgEvents'
  'GET /users/:username/received_events': 'getReceivedEvents'
  'GET /users/:username/received_events/public': 'getPublicReceivedEvents'
  'GET /users/:username/events': 'getUserPerformedEvents'
  'GET /users/:username/events/public': 'getPublicUserPerformedEvents'
  'GET /users/:username/events/orgs/:org': 'getOrgEvents'
