Namespace 'GitHub.api',
  'getNotifications': 'GET /notifications'
  'getNotificationsForRepo': 'GET /repos/:owner/:repo/notifications'
  'setNotificationsRead': 'PUT /notifications'
  'setRepoNotificationsRead': 'PUT /repos/:owner/:repo/notifications'
  'getThread': 'GET /notifications/threads/:id'
  'markThreadRead': 'PATCH /notifications/threads/:id'
  'isSubscribed': 'GET /notifications/threads/:id/subscription'
  'setSubscription': 'PUT /notifications/threads/:id/subscription'
  'deleteSubscription': 'DELETE /notifications/threads/:id/subscription'
