Namespace 'GitHub.api',
  'GET /notifications': 'getNotifications'
  'GET /repos/:owner/:repo/notifications': 'getNotificationsForRepo'
  'PUT /notifications': 'setNotificationsRead'
  'PUT /repos/:owner/:repo/notifications': 'setRepoNotificationsRead'
  'GET /notifications/threads/:id': 'getThread'
  'PATCH /notifications/threads/:id': 'markThreadRead'
  'GET /notifications/threads/:id/subscription': 'isSubscribed'
  'PUT /notifications/threads/:id/subscription': 'setSubscription'
  'DELETE /notifications/threads/:id/subscription': 'deleteSubscription'
